Allow ledger-reconcile-insert-effective-date to be a function
ledger/ledger-mode pull request #332
Opened 2022-05-16 02:52 UTC by bcc32

Allow the user to customize ledger-reconcile-insert-effective-date by making it
a function that is called with the point at the posting to be cleared.  This
allows the function to decide whether to insert an effective date based on,
e.g., the payee or the account in question.

This is kept backwards-compatible with existing boolean values, which just
behave as a constant-returning function.

2022-05-16 07:29 UTC, purcell requested changes

2022-05-16 07:29 UTC, purcell commented on ledger-reconcile.el
> +  "If `ledger-reconcile-insert-effective-date' is t, or returns
Would you mind making this comment conform to `checkdoc` please?

2022-05-16 07:29 UTC, purcell commented on ledger-reconcile.el
> +        (ledger-reconcile-insert-effective-date))
But surely here this might sometimes be a bool, not a function?

2022-05-22 20:35 UTC, bcc32 commented on ledger-reconcile.el
> +        (ledger-reconcile-insert-effective-date))
This is the function defined above, not the defcustom (otherwise I'd have to `funcall` it).

2022-05-22 20:38 UTC, bcc32 commented on ledger-reconcile.el
> +  "If `ledger-reconcile-insert-effective-date' is t, or returns
Got it, done!

2022-05-22 20:52 UTC, purcell commented on ledger-reconcile.el
> +        (ledger-reconcile-insert-effective-date))
Sorry, yes, ignore me. This seems fine as-is.

2022-05-22 20:54 UTC, merged